name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ou a branch que você deseja usar para o build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t nome-da-imagem .
          docker tag nome-da-imagem:latest username/nome-da-imagem:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push username/nome-da-imagem:latest
