name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build front-end Docker image
        run: |
          docker build -f Front/network-app/Dockerfile -t manuwenning/network-front .

      - name: Build back-end Docker image
        run: |
          docker build -f Back/NetworkChallenge/NetworkChallenge/Dockerfile -t manuwenning/network-back .

      - name: Push front-end Docker image
        run: |
          docker push manuwenning/network-front

      - name: Push back-end Docker image
        run: |
          docker push manuwenning/network-back

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy front-end application
        run: |
          ssh user@server "docker pull manuwenning/network-front:latest && docker run -d --name network-front manuwenning/network-front:latest"

      - name: Deploy back-end application
        run: |
          ssh user@server "docker pull manuwenning/network-back:latest && docker run -d --name network-back manuwenning/network-back:latest"
