name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build front-end Docker image
        run: |
          docker build -f Front/network-app/Dockerfile -t manuwenning/network-front .  # Substitua "username" pelo seu Docker Hub

      - name: Build back-end Docker image
        run: |
          docker build -f Back/NetworkChallenge/NetworkChallenge/Dockerfile -t manuwenning/network-back .  # Substitua "username" pelo seu Docker Hub

      - name: Push front-end Docker image
        run: |
          docker push manuwenning/network-front  # Substitua "username" pelo seu Docker Hub

      - name: Push back-end Docker image
        run: |
          docker push manuwenning/network-back  # Substitua "username" pelo seu Docker Hub
